baseURL = 'https://0xliam.github.io'
languageCode = 'en-us'
title = "liam's notes"
theme = "smol"

# Parameters
[params]
    subtitle = "âŒˆğš‘ğš’ğšğš‘ ğšğšğšŒğš‘ ğš•ğš˜ğš  ğš•ğš’ğšğšâŒ‹ âœ§ï½¥ï¾Ÿâ˜½Ëšï½¡âœ§ï½¡"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/0xliam"
        weight = 1 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/sushiipunk"
        weight = 2 